### ISSUE TITLE
New flood layers not found under the Flood icons on the homepage

### ISSUE THREAD

**Issue by vdeparday** [MalawiGeospatialTools/masdap#29]
There is a number of new flood layers for Mangochi and Karonga developed by Cima. However, they are not listed when clicking on the Flood icon on the homepage.

The flood keyword need to be added to all those layers. 

Sorry, I don't have the rights on the repo so I cannot add Gabriel in cc or assign anyone.

**Comment by sbsimo** [comment]
Keywords for Mangochi, Karonga and Salima flood layers were updated by adding the 'flood' keyword
