### ISSUE TITLE
Ansible role `ortelius.geonode` missing

### ISSUE THREAD

**Issue by stevenvandervalk** [MalawiGeospatialTools/masdap#33]
Hi!  I really like the project and use of geonode and looking to do something similar for a different open data project.  Went to try it out locally and noticed the ansible role no longer exists?  Is there any chance you could rehost it or advise how I could workaround.
Thanks!

**Comment by ppasq** [comment]
Sorry for the late reply. Ansible is not supported in the current version of MASDAP based on GeoNode 2.4.1. We are working on an upgrade based on 2.6 and Ansible should be likely used. Timing largely depends on the new GeoNode stable release. A new MASDAP will soon follow.

**Comment by stevenvandervalk** [comment]
Hi @ppasq, thanks for replying and the info.  I was hoping to try out modifying MASDAP theming now on a 2.4.1 vagrant.  Is it possible you have a working procedure I could use to apply it / or does it roughly follow the [GeoNode theming docs](http://docs.geonode.org/en/master/tutorials/admin/customize_lookfeel/customize/theme_admin.html#theme-admin)?  Or should I wait until new MASDAP and GeoNode versions because you are intending lots of breaking changes?  Thanks.
