### ISSUE TITLE
Add masdap.mw (without www) to DNS record

### ISSUE THREAD

**Issue by vdeparday** [MalawiGeospatialTools/masdap#36]
Can we make http://masdap.mw/ point toward http://www.masdap.mw ? Or the other way around but right now the URL http://masdap.mw is dead.

**Comment by surveysmalawi** [comment]
Masdap.mw has never worked.  www.masdap.mw has always been the site

I agree that both should be set up.

Justin

Whatsapp: +44 7956 285077
Skype: lotfrance 
French mob: +33 768 751 750
UK mob: +44 7956 285077
Malawi mob: +265 998 557007

**Comment by ppasq** [comment]
@surveysmalawi Brown followed the domain configuration with the ISP provider, so he can help.

**Comment by ppasq** [comment]
The masdap.mw is redirecting to www.masdap so I'm closing this issue.
