### ISSUE TITLE
Map composer zoom breaks

### ISSUE THREAD

**Issue by rbanick** [MalawiGeospatialTools/masdap#38]
When using the map composer, adding a new layer from the GeoServer WMS disables most zoom functionality. Mouse-based zoom is disabled while the map composer zoom in/out buttons _mostly_ don't work. Zoom to previous extent does appear to work but the layer disappear after a certain number of uses.

**Comment by ppasq** [comment]
The map composer has been changed to MapStore2. The problem should not occur anymore.
