### ISSUE TITLE
Add major Government agencies logos

### ISSUE THREAD

**Issue by ppasq** [MalawiGeospatialTools/masdap#4]
In site_base.html Government agencies involved in MASDAP shall be added.

**Comment by ppasq** [comment]
@GumbiGumbi could you pls provide the list of Gov agencies and related logos/links?

**Comment by GumbiGumbi** [comment]
ppasq, I acknowledge the assignment to me. However I might take long to respond to it as I am travelling to the UK to pursue my MSc. I will refer the issue to a colleague.

**Comment by ppasq** [comment]
Closing as obsolete.
