### ISSUE TITLE
Registration requests from random users

### ISSUE THREAD

**Issue by cgiovando** [MalawiGeospatialTools/masdap#52]
Since v2.10 upgrade, there has been a series of registration requests from users with random names and domains (yandex.ru, mail.ru, yandex.com, ttmail.pro, funnetwork.xyz, streamweb.ru)

We should consider other spam prevention methods (in addition to captcha) or rethink how to allow new legit users to register.

**Comment by ppasq** [comment]
The issue is the site not validating reCaptcha. I'm going to fix this.

**Comment by cgiovando** [comment]
@afabiani - can you please review and merge @ppasq's PR https://github.com/MalawiGeospatialTools/masdap/pull/57?
