### ISSUE TITLE
Review of suspicious registered users

### ISSUE THREAD

**Issue by cgiovando** [MalawiGeospatialTools/masdap#53]
There are almost 1500 active users registered in Masdap at the moment. Many of those may not be legit, with suspicious names and email addresses.

I would suggest a full review and purge of all unknown users.

Related to #52 we should consider a different registration method that prevents users from being automatically added and marked as active.

**Comment by ppasq** [comment]
The users have been reviewed and suspicious accounts have been purge. However some may still be present. A double check by the Masdap admins is needed.
